# Generated by Django 4.2.2 on 2023-07-15 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelOnCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('dataset_file_name', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_info', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MLMODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('model_zip_file', models.FilePathField(default='/')),
                ('creation_time', models.DateTimeField()),
                ('model_main_metric_name', models.CharField(default='UDEFINED METRIC', max_length=100)),
                ('model_main_metric_value', models.FloatField(default=0)),
                ('model_task_type', models.CharField(default='UNDEFINED TASK TYPE', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('task_type', models.CharField(max_length=100)),
                ('target_variable', models.CharField(max_length=100)),
                ('dataset_source_file_name', models.FilePathField(default='/')),
                ('GPU_SERVER_IP', models.CharField(max_length=20)),
                ('success', models.IntegerField()),
                ('main_metric_name', models.CharField(default='Undefined', max_length=20)),
                ('request_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExploitTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file_name', models.FilePathField()),
                ('GPU_SERVER_IP', models.CharField(max_length=20)),
                ('success', models.BooleanField(default=False)),
                ('result_file_name', models.FilePathField()),
                ('request_time', models.DateTimeField()),
                ('ml_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.mlmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
