# Generated by Django 4.2.2 on 2023-07-14 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelOnCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('dataset_file_name', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FILE_PATH', models.FilePathField()),
                ('UPLOAD_TOKEN', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingGpuRemoteServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP_ADDRESS', models.CharField(max_length=20, unique=True)),
                ('LAST_REQUEST', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_info', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MLMODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('config_best_json_file', models.FilePathField()),
                ('encoder_best_file', models.FilePathField()),
                ('scaler_best_file', models.FilePathField()),
                ('model_best_file', models.FilePathField()),
                ('creation_time', models.DateTimeField()),
                ('ready_to_use', models.BooleanField(default=False)),
                ('valid_token_to_upload_files', models.CharField(default='', max_length=100)),
                ('model_main_metric_name', models.CharField(default='UDEFINED METRIC', max_length=100)),
                ('model_main_metric_value', models.FloatField(default=0)),
                ('model_task_type', models.CharField(default='UNDEFINED TASK TYPE', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('task_type', models.CharField(max_length=100)),
                ('target_variable', models.CharField(max_length=100)),
                ('upload_token', models.CharField(max_length=100)),
                ('GPU_server_IP', models.CharField(max_length=20)),
                ('success', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExploitTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file_name', models.FilePathField()),
                ('GPU_SERVER_IP', models.CharField(max_length=20)),
                ('success', models.BooleanField(default=False)),
                ('result_file_name', models.FilePathField()),
                ('ml_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.mlmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
