# Generated by Django 4.2.2 on 2023-07-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadtokens',
            name='FILE_PATH',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
