# Generated by Django 4.2.2 on 2023-07-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_delete_exploitresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='model_main_metric_name',
            field=models.CharField(default='UDEFINED METRIC', max_length=100),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='model_main_metric_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='model_task_type',
            field=models.CharField(default='UNDEFINED TASK TYPE', max_length=20),
        ),
    ]
